version: '3'

tasks:
  send_credentials_to_slack:
    desc: Send ephemeral credentials to slack
    cmds:
      - curl -X POST --data-urlencode "payload={'channel'":" '#github-actions-tests', 'username'":" 'webhookbot', 'text'":" '`cat credentials.txt`', 'icon_emoji'":" ':github:'}" {{.SLACK_WEBHOOK_URL}}


  cleanup:
    desc: Shared items that can be cleaned up
    cmds:
      - terraform destroy --auto-approve -target=module.tfc || true
      - rm -rf *terraform*
      - rm -rf .terraform*
      - rm -rf ~/.kube/
      - rm -rf credentials.txt
      - rm -rf ~/.aws/


  admiral:
    desc: Using the ADMIRAL context
    cmds:
      - kubectl config use-context {{.ADMIRAL_CLUSTER_NAME}}

  captain:
    desc: Using the CAPTAIN context
    cmds:
      - kubectl config use-context {{.CAPTAIN_CLUSTER_NAME}}

      